# Generated by Django 6.0.3 on 2026-03-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.CharField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('regular', 'Regular'), ('medium', 'Medium'), ('high', 'High')], default='regular', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
